FROM ubuntu:22.04

# Handy packages
RUN apt-get update && apt-get install -y libpq-dev gcc postgresql-client sqlite3 zip less curl python3 python3-pip

# NPM and Yarn, for the website
WORKDIR /root
RUN curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
RUN npm install --global yarn

# Python deps
WORKDIR /iatitables
COPY requirements_dev.txt .
RUN pip install -r requirements_dev.txt

ENTRYPOINT ["sleep", "infinity"]
