services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/iatitables
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    entrypoint: sleep infinity
    ports:
      - 8000:8000
      - 8001:8001
      - 8080:8080

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432

volumes:
  postgres-data:
